export { default as Header } from './Header/index'
export { default as Step1 } from './Step1/index'
export { default as Step2 } from './Step2/index'
export { default as ResultPage } from './ResultPage/index'
export { default as MainContainer } from './MainContainer/index'
export { default as Form } from './Form/index'
export { default as PrimaryButton } from './PrimaryButton/index'
